"""Constants for Virtueller Stromzähler."""

DOMAIN = "stromzaehler"

CONF_PHASE_A          = "phase_a"
CONF_PHASE_B          = "phase_b"
CONF_PHASE_C          = "phase_c"
CONF_PHASE_A_RETURNED = "phase_a_returned"
CONF_PHASE_B_RETURNED = "phase_b_returned"
CONF_PHASE_C_RETURNED = "phase_c_returned"
CONF_SOLAR            = "solar"
CONF_BATT_CHARGE      = "battery_charge"
CONF_BATT_DISCHARGE   = "battery_discharge"
CONF_BATT_NET         = "battery_net"
CONF_METER_BASIS      = "meter_basis"
CONF_PHASE_OFFSET     = "phase_offset"
